config/routes.rb
Rails.application.routes.draw do
  resources :paiements
  devise_for :users
  resources :histories
  resources :abonnements
  resources :customers
  resources :codes
  resources :kits
  root to: 'home#index'
  scope :admin do
    get 'users', to: "home#users"
    match 'add_user', to: "home#add_new_user", via: [:get, :post  ]
    get 'abonnements_paiement', to: "home#abonnement_paiements"
    get 'make_virements', to: "home#make_virement"
  end
  scope :api, defaults: {format: :json} do
    scope :v1 do
      # check kit ID
      get "check_kit/:code_barre", to: "api#verify_kit"
      get "request_authorization", to: "api#request_authorization"
      get "save_api_paiement", to: "api#save_api_paiement"
      get "search_customer/:phone", to: "api#search_customer"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/history.rb
class History < ApplicationRecord
  has_many :abonnements
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_history, only: %i[ show edit update destroy ]

  # GET /histories or /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1 or /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories or /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to history_url(@history), notice: "History was successfully created." }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1 or /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to history_url(@history), notice: "History was successfully updated." }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1 or /histories/1.json
  def destroy
    @history.destroy

    respond_to do |format|
      format.html { redirect_to histories_url, notice: "History was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def history_params
      params.require(:history).permit(:abonnement_id, :amount, :transaction_id, :payment_mode)
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_with(model: history, class: "contents") do |form| %>
  <% if history.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
        <% history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :abonnement_id %>
    <%= form.text_field :abonnement_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :amount %>
    <%= form.text_field :amount, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :transaction_id %>
    <%= form.text_field :transaction_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :payment_mode %>
    <%= form.text_field :payment_mode, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/histories/_history.html.erb
<div id="<%= dom_id history %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Abonnement:</strong>
    <%= history.abonnement_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Amount:</strong>
    <%= history.amount %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Transaction:</strong>
    <%= history.transaction_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Payment mode:</strong>
    <%= history.payment_mode %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this history", history, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this history', edit_history_path(history), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/histories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing history</h1>

  <%= render "form", history: @history %>

  <%= link_to "Show this history", @history, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to histories", histories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/histories/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Histories</h1>
    <%= link_to 'New history', new_history_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="histories" class="min-w-full">
    <%= render @histories %>
  </div>
</div>

app/views/histories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New history</h1>

  <%= render "form", history: @history %>

  <%= link_to 'Back to histories', histories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/histories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @history %>

    <%= link_to 'Edit this history', edit_history_path(@history), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this history', history_path(@history), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to histories', histories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>