config/routes.rb
Rails.application.routes.draw do
  resources :paiements
  devise_for :users
  resources :histories
  resources :abonnements
  resources :customers
  resources :codes
  resources :kits
  root to: 'home#index'
  scope :admin do
    get 'users', to: "home#users"
    match 'add_user', to: "home#add_new_user", via: [:get, :post  ]
    get 'abonnements_paiement', to: "home#abonnement_paiements"
    get 'make_virements', to: "home#make_virement"
  end
  scope :api, defaults: {format: :json} do
    scope :v1 do
      # check kit ID
      get "check_kit/:code_barre", to: "api#verify_kit"
      get "request_authorization", to: "api#request_authorization"
      get "save_api_paiement", to: "api#save_api_paiement"
      get "search_customer/:phone", to: "api#search_customer"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/code.rb
class Code < ApplicationRecord
  # url_for helper
  include Rails.application.routes.url_helpers

  belongs_to :kit
  validates :cle, presence: true, uniqueness: {message: "Cette valeur à déja été enregistrée"}

  has_one_attached :barcode
  has_one_attached :qr_code

  after_create :generate_code
  after_create :generate_qr

  def generate_qr

    # ensure rqrcode works here
    require "rqrcode"

    # https://superails.com/products/5?abc=d+e+f
    qr_url = url_for(controller: 'kits',
                     action: 'show',
                     id: self.cle,
                     host: 'superails.com',
                     only_path: false,
                     abc: 'd e f'
    )

    # generate QR code
    qr_code = RQRCode::QRCode.new(qr_url)

    # QR code to image
    qr_png = qr_code.as_png(
      bit_depth: 1,
      border_modules: 4,
      color_mode: ChunkyPNG::COLOR_GRAYSCALE,
      color: "black",
      file: nil,
      fill: "white",
      module_px_size: 6,
      resize_exactly_to: false,
      resize_gte_to: false,
      size: 120
    )

    # name the image
    image_name = "qr_#{SecureRandom.hex}"

    # save the image in TMP
    image = IO.binwrite("tmp/storage/#{image_name}.png", qr_png.to_s)

    # save TMP file to ActiveStorage
    blob = ActiveStorage::Blob.create_after_upload!(
      io: File.open("tmp/storage/#{image_name}.png"),
      filename: image_name,
      content_type: 'png'
    )

    # attach ActiveStorage::Blob to the product
    self.qr_code.attach(blob)

  end

  def generate_code

    require 'barby'
    require 'barby/barcode/code_128'
    require 'barby/outputter/ascii_outputter'
    require 'barby/outputter/png_outputter'

    barcoded = Barby::Code128B.new(self.cle)

    # chunky_png required for THIS action
    png = Barby::PngOutputter.new(barcoded).to_png

    image_name = SecureRandom.hex

    IO.binwrite("tmp/#{image_name}.png", png.to_s)

    blob = ActiveStorage::Blob.create_after_upload!(
      io: File.open("tmp/#{image_name}.png"),
      filename: image_name,
      content_type: 'png'
    )

    self.barcode.attach(blob)
  end
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_code, only: %i[ show edit update destroy ]

  # GET /codes or /codes.json
  def index
    @codes = Code.all
  end

  # GET /codes/1 or /codes/1.json
  def show
  end

  # GET /codes/new
  def new
    @code = Code.new
  end

  # GET /codes/1/edit
  def edit
  end

  # POST /codes or /codes.json
  def create
    @code = Code.new(code_params)

    respond_to do |format|
      if @code.save
        format.html { redirect_to kit_path(@code.kit_id), notice: "Code was successfully created." }
        format.json { render :show, status: :created, location: @code }
      else
        puts @code.errors.details
        format.html { redirect_to kit_path(@code.kit_id), status: :unprocessable_entity }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /codes/1 or /codes/1.json
  def update
    respond_to do |format|
      if @code.update(code_params)
        format.html { redirect_to code_url(@code), notice: "Code was successfully updated." }
        format.json { render :show, status: :ok, location: @code }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /codes/1 or /codes/1.json
  def destroy
    @code.destroy

    respond_to do |format|
      format.html { redirect_to kit_path(@code.kit_id), notice: "Code was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_code
      @code = Code.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def code_params
      params.require(:code).permit(:cle, :validite, :kit_id)
    end
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/views/codes/_code.html.erb
<div id="<%= dom_id code %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Cle:</strong>
    <%= code.cle %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Validite:</strong>
    <%= code.validite %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Kits:</strong>
    <%= code.kits_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this code", code, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this code', edit_code_path(code), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/codes/_form.html.erb
<%= form_with(model: code, class: "w-full max-w-lg") do |form| %>
  <% if code.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(code.errors.count, "error") %> prohibited this code from being saved:</h2>

      <ul>
        <% code.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="my-5">
    <%= form.label "ID Kit (identifiant du kit)" %>
    <%= form.text_field :cle_identifiant, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", value: Kit.find(params[:kit_id]).code_barre, readonly: true %>
  </div>

  <div class="my-5">
    <%= form.label :cle %>
    <%= form.number_field :cle, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "Code du kit", required: true %>
  </div>

  <div class="my-5">
    <%= form.label :validite %>
    <%= form.date_field :validite, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :kits_id %>
    <%= form.hidden_field :kit_id, value: Kit.find(params[:kit_id]).id %>
    <%= form.text_field :kit_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", value: Kit.find(params[:kit_id]).name, readonly: true %>
  </div>

  <div class="inline">
    <%= form.submit 'Ajouter un nouveau code', class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>
,

app/views/codes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing code</h1>

  <%= render "form", code: @code %>

  <%= link_to "Show this code", @code, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to codes", codes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/codes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Codes</h1>
    <%= link_to 'New code', new_code_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="codes" class="min-w-full">
    <%= render @codes %>
  </div>
</div>

app/views/codes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New code</h1>

  <%= render "form", code: @code %>

  <%= link_to 'Back to codes', codes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/codes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @code %>

    <%= link_to 'Edit this code', edit_code_path(@code), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this code', code_path(@code), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to codes', codes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>