config/routes.rb
Rails.application.routes.draw do
  resources :paiements
  devise_for :users
  resources :histories
  resources :abonnements
  resources :customers
  resources :codes
  resources :kits
  root to: 'home#index'
  scope :admin do
    get 'users', to: "home#users"
    match 'add_user', to: "home#add_new_user", via: [:get, :post  ]
    get 'abonnements_paiement', to: "home#abonnement_paiements"
    get 'make_virements', to: "home#make_virement"
  end
  scope :api, defaults: {format: :json} do
    scope :v1 do
      # check kit ID
      get "check_kit/:code_barre", to: "api#verify_kit"
      get "request_authorization", to: "api#request_authorization"
      get "save_api_paiement", to: "api#save_api_paiement"
      get "search_customer/:phone", to: "api#search_customer"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/abonnement.rb
class Abonnement < ApplicationRecord
  belongs_to :customer
  belongs_to :kit
  has_many :paiements

  validates :kit_id, presence: true, uniqueness: {message: "Ce kit est déja attribué à un client"}
  validates :customer_id, presence: true

  before_save :generate_token, if: :new_record?

  def generate_token
    self.token = SecureRandom.hex(10)
  end
end

app/controllers/abonnements_controller.rb
class AbonnementsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_abonnement, only: %i[ show edit update destroy ]

  # GET /abonnements or /abonnements.json
  def index
    @abonnements = Abonnement.all.order(created_at: :desc)
  end

  # GET /abonnements/1 or /abonnements/1.json
  def show
  end

  # GET /abonnements/new
  def new
    @abonnement = Abonnement.new
  end

  # GET /abonnements/1/edit
  def edit
  end

  # POST /abonnements or /abonnements.json
  def create
    @abonnement = Abonnement.new(abonnement_params)

    respond_to do |format|
      if @abonnement.save
        format.html { redirect_to abonnement_url(@abonnement), notice: "Abonnement was successfully created." }
        format.json { render :show, status: :created, location: @abonnement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @abonnement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abonnements/1 or /abonnements/1.json
  def update
    respond_to do |format|
      if @abonnement.update(abonnement_params)
        format.html { redirect_to abonnement_url(@abonnement), notice: "Abonnement was successfully updated." }
        format.json { render :show, status: :ok, location: @abonnement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @abonnement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abonnements/1 or /abonnements/1.json
  def destroy
    @abonnement.destroy

    respond_to do |format|
      format.html { redirect_to abonnements_url, notice: "Abonnement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abonnement
      @abonnement = Abonnement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def abonnement_params
      params.require(:abonnement).permit(:customer_id, :kit_id, :active)
    end
end

app/helpers/abonnements_helper.rb
module AbonnementsHelper
end

app/views/abonnements/_abonnement.html.erb
<div id="<%= dom_id abonnement %>">

<style>
  data-title]:hover:after {
      opacity: 1;
      transition: all 0.1s ease 0.5s;
      visibility: visible;
  }
  [data-title]:after {
      content: attr(data-title);
      background-color: #00FF00;
      color: #111;
      font-size: 150%;
      position: absolute;
      padding: 1px 5px 2px 5px;
      bottom: -1.6em;
      left: 100%;
      white-space: nowrap;
      box-shadow: 1px 1px 3px #222222;
      opacity: 0;
      border: 1px solid #111111;
      z-index: 99999;
      visibility: hidden;
  }
  [data-title] {
      position: relative;
  }
</style>

  <tr>
    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm sm:pl-6" data-title="My site" title="Ajouté le : <%= ApplicationHelper.format_date(abonnement.created_at) %>">
      <div class="flex items-center">
        <div class="h-10 w-10 flex-shrink-0">
          <%= image_tag "sunland.png", class: "h-10 w-10 rounded-full" %>
        </div>
        <div class="ml-4">
          <div class="font-medium text-gray-900"><%= "#{abonnement.customer.name} #{abonnement.customer.second_name}" %></div>
          <div class="text-gray-500"><%= link_to abonnement.customer.token, customer_path(abonnement.customer), class: "hover:text-yellow-500" %></div>
        </div>
      </div>
    </td>
    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
      <div class="text-gray-900"><%= abonnement.kit.name %></div>
      <div class="text-gray-500">Optimization</div>
    </td>
    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
      <span class="inline-flex rounded-full bg-green-100 px-2 text-xs font-semibold leading-5 text-green-800">
        <%= abonnement.active? ? "Activé": "Inactivé" %>
      </span>
    </td>
    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
      <div class="text-gray-900 mb-2"><%= @percentage = ((abonnement.paiements.sum(:amount).to_f / abonnement.kit.amount.to_f) * 100).round(2)  %>%
      </div>
      <div class="text-gray-500">
        <div class="w-full bg-gray-200 rounded-full">
          <div class="bg-yellow-600 text-xs font-medium text-blue-100 text-center p-0.5 leading-none rounded-l-full" style="width: <%= @percentage %>%"> <%= "#{@percentage}%" %></div>
        </div>
      </div>
    </td>
    <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
      <%= link_to "Afficher", abonnement, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to 'Editer', edit_abonnement_path(abonnement), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    </td>
  </tr>

</div>

app/views/abonnements/_form.html.erb
<%= form_with(model: abonnement, class: "contents") do |form| %>
  <% if abonnement.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(abonnement.errors.count, "error") %> prohibited this abonnement from being saved:</h2>

      <ul>
        <% abonnement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :customer_id %>
    <%= form.select( :customer_id, Customer.all.collect {|p| [ p.name, p.id ] }, {class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", prompt: 'Select customer', label: false}) %>
  </div>

  <div class="my-5">
    <%= form.label :kit_id %>
    <%#= form.text_field :kit_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <%= form.select( :kit_id, Kit.all.collect {|p| [ p.name, p.id ] }, {class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", prompt: 'Select customer', label: false}) %>
  </div>

  <div class="my-5">
    <%= form.label :active %>
    <%= form.check_box :active, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/abonnements/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing abonnement</h1>

  <%= render "form", abonnement: @abonnement %>

  <%= link_to "Show this abonnement", @abonnement, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to abonnements", abonnements_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/abonnements/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div id="abonnements" class="min-w-full">
    <!-- This example requires Tailwind CSS v2.0+ -->
    <div class="-px-4 sm:px-6 lg:px-8">
      <div class="sm:flex sm:items-center">
        <div class="sm:flex-auto">
          <h1 class="text-xl font-semibold text-gray-900">Abonnement clients</h1>
          <p class="mt-2 text-sm text-gray-700">Trouvez ici la liste des abonnements client et leur evolution en fonction des clients.</p>
        </div>
        <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
          <%= link_to "Nouvel abonnement", new_abonnement_path, method: :get, data: { turbo_frame: 'modal' }, class: "inline-flex items-center justify-center rounded-md border border-transparent bg-gray-600 px-4 py-2 text-sm font-medium text-yellow-500 shadow-sm hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 sm:w-auto" %>
        </div>
      </div>
      <div class="mt-8 flex flex-col">
        <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
            <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
              <table class="min-w-full divide-y divide-gray-300">
                <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Identité client</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Libellé kit</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Status</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">% paiement</th>
                  <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                    <span class="sr-only">Edit</span>
                  </th>
                </tr>
                </thead>
                <tbody class="divide-y divide-gray-200 bg-white">

                <%= render @abonnements %>

                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/abonnements/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New abonnement</h1>

    <%= render "form", abonnement: @abonnement %>

  <%= link_to 'Back to abonnements', abonnements_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/abonnements/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <!-- This example requires Tailwind CSS v2.0+ -->
    <div>
      <div>
        <h3 class="text-lg leading-6 font-medium text-gray-900"><%= @abonnement.token %></h3>
        <p class="mt-1 max-w-2xl text-sm text-gray-500">Indentification de l'abonnement.</p>
      </div>
      <div class="mt-5 border-t border-gray-200">
        <dl class="sm:divide-y sm:divide-gray-200">
          <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
            <dt class="items-center flex text-sm font-medium text-gray-500">
              <svg class="w-6 h-6 text-yellow-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
              </svg>
              Client
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 text-right"><%= link_to ("#{@abonnement.customer.name} #{@abonnement.customer.second_name}"), customer_path(@abonnement.customer), class: "hover:text-yellow-500" %></dd>
          </div>
          <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
            <dt class="text-sm font-medium text-gray-500 items-center flex">
              <svg class="w-6 h-6 text-yellow-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 9l3 3-3 3m5 0h3M5 20h14a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
              </svg>
              Identification client
            </dt>
            <dd class="mt-1 text-right text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= link_to @abonnement.customer.token, customer_path(@abonnement.customer), class: "hover:text-yellow-500" %></dd>
          </div>
          <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
            <dt class="text-sm font-medium text-gray-500 items-center flex">
              <svg class="w-6 h-6 text-yellow-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 18h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z"></path>
              </svg>
              Identification kit
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 text-right"><%= link_to @abonnement.kit.token, kit_path(@abonnement.kit), class: "hover:text-yellow-600" %></dd>
          </div>
          <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
            <dt class="text-sm font-medium text-gray-500 items-center flex">
              <svg class="w-6 h-6 text-yellow-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path>
              </svg>
              Libellé Kit
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 text-right"><%= @abonnement.kit.name %></dd>
          </div>
          <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
            <dt class="text-sm font-medium text-gray-500 items-center flex">
              <svg class="w-6 h-6 text-yellow-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z"></path>
              </svg>
              Montant du kit
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 text-right"><%= ApplicationHelper.format_money(@abonnement.kit.amount) %></dd>
          </div>
          <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
            <dt class="text-sm font-medium text-gray-500 items-center flex">
              <svg class="w-6 h-6 text-yellow-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"></path>
              </svg>
              Montant déja payé
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 text-right"><%= ApplicationHelper.format_money(@abonnement.paiements.sum(:amount)) %></dd>
          </div>
          <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
            <dt class="text-sm font-medium text-gray-500 items-center flex">
              <svg class="w-6 h-6 text-yellow-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z"></path>
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z"></path>
              </svg>
              Pourcentage paiement
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 text-right"><%= ((@abonnement.paiements.sum(:amount).to_f / @abonnement.kit.amount.to_f) * 100).round(2) %>
              %
            </dd>
          </div>
          <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
            <dt class="text-sm font-medium text-gray-500 items-center flex">
              <svg class="w-6 h-6 text-yellow-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01"></path>
              </svg>
              Historique de paiement
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 text-right"><%= link_to "Voir tous les paiements", abonnements_paiement_path(abonnement_id: @abonnement.id), class: "hover:text-yellow-500" %></dd>
          </div>
          <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
            <dt class="text-sm font-medium text-gray-500">About</dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 text-right">Fugiat ipsum ipsum deserunt culpa
              aute sint do
              nostrud anim incididunt cillum culpa consequat. Excepteur qui ipsum aliquip consequat sint. Sit id mollit
              nulla mollit nostrud in ea officia proident. Irure nostrud pariatur mollit ad adipisicing reprehenderit
              deserunt qui eu.
            </dd>
          </div>
          <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
            <dt class="text-sm font-medium text-gray-500">Factures numériques</dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
              <ul role="list" class="border border-gray-200 rounded-md divide-y divide-gray-200">
                <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm">
                  <div class="w-0 flex-1 flex items-center">
                    <!-- Heroicon name: solid/paper-clip -->
                    <svg class="flex-shrink-0 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M8 4a3 3 0 00-3 3v4a5 5 0 0010 0V7a1 1 0 112 0v4a7 7 0 11-14 0V7a5 5 0 0110 0v4a3 3 0 11-6 0V7a1 1 0 012 0v4a1 1 0 102 0V7a3 3 0 00-3-3z" clip-rule="evenodd"/>
                    </svg>
                    <span class="ml-2 flex-1 w-0 truncate"> resume_back_end_developer.pdf </span>
                  </div>
                  <div class="ml-4 flex-shrink-0">
                    <a href="#" class="font-medium text-indigo-600 hover:text-indigo-500"> Download </a>
                  </div>
                </li>
                <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm">
                  <div class="w-0 flex-1 flex items-center">
                    <!-- Heroicon name: solid/paper-clip -->
                    <svg class="flex-shrink-0 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M8 4a3 3 0 00-3 3v4a5 5 0 0010 0V7a1 1 0 112 0v4a7 7 0 11-14 0V7a5 5 0 0110 0v4a3 3 0 11-6 0V7a1 1 0 012 0v4a1 1 0 102 0V7a3 3 0 00-3-3z" clip-rule="evenodd"/>
                    </svg>
                    <span class="ml-2 flex-1 w-0 truncate"> coverletter_back_end_developer.pdf </span>
                  </div>
                  <div class="ml-4 flex-shrink-0">
                    <a href="#" class="font-medium text-indigo-600 hover:text-indigo-500"> Download </a>
                  </div>
                </li>
              </ul>
            </dd>
          </div>
        </dl>
      </div>
    </div>


    <%#= render @abonnement %>

    <%= link_to 'Edit this abonnement', edit_abonnement_path(@abonnement), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this abonnement', abonnement_path(@abonnement), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to abonnements', abonnements_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>